export { default as Footer } from "./Footer";
export { default as Body } from "./Body";
export { default as Header } from "./Header";
export { default as RestaurantCard } from "./RestaurantCard";
export { default as Shimmer } from "./Shimmer";
export { default as About } from "./About";
export { default as Error } from "./Error";
export { default as Contact } from "./Contact";
export { default as Profile } from "./Profile";